export enum ActionTypes {
  REQUEST_LOGIN = 'auth/REQUEST_LOGIN',
  SUCCESS_LOGIN = 'auth/SUCCESS_LOGIN',
  FAILURE_LOGIN = 'auth/FAILURE_LOGIN',
  REQUEST_LOGOUT = 'auth/REQUEST_LOGOUT',
  SUCCESS_LOGOUT = 'auth/SUCCESS_LOGOUT',
  FAILURE_LOGOUT = 'auth/FAILURE_LOGOUT',
}
